# Generated by Django 5.2.13 on 2026-04-22 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Applied', 'applied'), ('Approved', 'approved'), ('Rejected', 'rejected')], max_length=30)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leaverequest')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
