# Generated by Django 5.2.13 on 2026-04-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavelog',
            old_name='performed_by',
            new_name='approved_by',
        ),
    ]
