# Generated by Django 5.2.13 on 2026-04-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_rename_performed_by_leavelog_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Approved', 'approved'), ('Rejected', 'rejected'), ('Pending', 'pending')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(choices=[('Sick', 'sick'), ('Casual', 'Casual'), ('Paid', 'Paid')], max_length=30),
        ),
    ]
